version: 2

branches:
  - name: master
    description: 3.x - for Java SDK 5.0+, uses AWS 2.x
  - name: 2.x
    description: for Java SDK 4.x, uses AWS 2.x
  - name: aws-v1
    description: uses AWS 1.x, allows Java 7

publications:
  - url: https://oss.sonatype.org/content/groups/public/com/launchdarkly/launchdarkly-java-server-sdk-dynamodb-store/
    description: Sonatype
  - url: https://javadoc.io/doc/com.launchdarkly/launchdarkly-java-server-sdk-dynamodb-store
    description: documentation (javadoc.io)

jobs:
  - docker:
      image: gradle:7.3.3-jdk8
    template:
      name: gradle
    skip:
      - test  # Running the unit tests would require installing DynamoDB. They've already been run in CI.

documentation:
  gitHubPages: true
